name: CI

on:
  push:

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
            
      - name: install requirements
        run: pip install -r app/requirements.txt

      - name: testing flake8
        run: flake8 app/

      - name: make docker image
        run: docker build -t py-monitor .
